### PR TITLE
Help modal styling

### PR DESCRIPTION
**Pull request by bhalt**
Clean up styling, layout, and language to maintain consistency on the Help Modal across the platform.

### CODE REVIEW

**Comment by clarkjefcoat** [comment]
I don't understand why, but in Chrome, FF, and IE11 this iframe is 550px high even though the code says 500px.

**Comment by clarkjefcoat** [comment]
This size strangeness appears to be related to the ".modal-body > iframe", "min-height" setting in ozpwebtop-1.0.7.css which comes from src/sass/main.scss.

**Comment by bhalt** [comment]
Great catch! Thanks, @clarkjefcoat - css override removed, as well as some additional unnecessary Webtop overrides.

**Comment by clarkjefcoat** [comment]
:+1:

**Comment by hoganmaps** [comment]
naet :+1:

**Pull request merged**
