### PR TITLE
fix(profileModel)put real data in modal for new backend #534

### PR DESCRIPTION
**Pull request by SOAP1914**
@clarkjefcoat @wski

### CODE REVIEW

**Comment by SOAP1914** [comment]
**Before**
screen shot 2016-03-15 at 5 32 49 pm

**After**
screen shot 2016-03-15 at 5 32 27 pm

**Comment by clarkjefcoat** [comment]
Updated screenshot and OzoneConfig.js.

**Comment by clarkjefcoat** [comment]
:+1:

**Comment by tonyalletag** [comment]
:+1:

**Pull request merged**
