### PR TITLE
style(chromeBar,new bootstrap): updating to ozp-bootstrap master branch, modifying the chrome-controls to remove minimize widgets, fix recent addApplicatons bug. #636, #595, #632

### PR DESCRIPTION
**Pull request by hoganmaps**
Small/related fixs for:

Using master branch for ozp-bootstrap (#632)
Updates to widget chrome (#595)
Bug with add applications from applications modal (#636)

### CODE REVIEW

**Comment by arw180** [comment]
This appears to fix the problem adding new apps to dashboards :+1:

**Comment by SOAP1914** [comment]
So are we getting rid of the highlight frame(blue glow around frame) in both grid and desktop view? Because I don't see it anymore in grid view

**Comment by hoganmaps** [comment]
https://github.com/ozone-development/ozp-webtop/issues/596

**Comment by wski** [comment]
Looks good to me :+1:

**Pull request merged**
