### PR TITLE
feat(Menu): Add helpdesk link to dropdown menu

### PR DESCRIPTION
**Pull request by clarkjefcoat**
#613

### CODE REVIEW

**Comment by wski** [comment]
:+1:

**Comment by hoganmaps** [comment]
@clarkjefcoat did you mean to apply the caboose class to the helpdesk link?
screen shot 2015-08-04 at 11 04 04 am

**Comment by hoganmaps** [comment]
:+1: if you did, the menu looks a little bottom heavy with both 'Submit Feedback' and 'Contact Help Desk'

**Comment by clarkjefcoat** [comment]
Ok, thanks.  I will revisit look and feel in the next iteration.

**Pull request merged**
