### PR TITLE
Fix(OZONEConfig): Update to localhost

### PR DESCRIPTION
**Pull request by sdeighan**
Updating the OZONEConfig file to use localhost addresses instead of
github.io to avoid infrastructure issues

### CODE REVIEW

**Comment by SOAP1914** [comment]
After talking to the team this pull request may cause problems in other files and we deleted the Help URL link for the code. (helpModal)

**Comment by sdeighan** [comment]
Github.io doesn’t even work - I don’t really care about the specific file, but having it all link to a broken site is just torturous when people (like me) try to build it. It doesn’t work how it is - there’s no way to update it with localhost so that it does work?


Sarah Deighan, UX Engineer
AppsMall / OZONE Project
work (443) 393-7109 | cell (408) 981-9733 | sarah.deighan@nextcentury.com<mailto:sarah.deighan@nextcentury.com>
NEXTCENTURYCORPORATION | main (443) 545-3100 | fax (443) 285-0799 | www.nextcentury.com<http://www.nextcentury.com/>

On Jun 22, 2015, at 3:34 PM, Ricardo James <notifications@github.com<mailto:notifications@github.com>> wrote:


After talking to the team this pull request may cause problems in other files and we deleted the Help URL link for the code. (helpModal)

**Comment by mparizernc** [comment]
I am fine if the team wants to leave the URLs, but I have concerns that someone believes that changing a configurable URL will cause problems in other files.  This url gets changed in any installed instance so why would it not cause problems there?  Also the URLs that are currently there point to a broken site which should cause issues the way it is now.

**Comment by arw180** [comment]
To clarify, the problem here is that we have a lot of development scripts (vagrant, CI boxes, Jenkins, etc), that contain `sed` commands to modify that file, and those commands could potentially break if we change the default contents of this file. Given that, I think it's best we forego these changes, since the added benefit is fairly minimal.

**Pull request closed without merging**
