### PR TITLE
fix(NavBar): Fixes navbar not working for APPS_MALL_STEWARD

### PR DESCRIPTION
**Pull request by wski**

### CODE REVIEW

**Comment by SOAP1914** [comment]
:+1: simple change

**Comment by wski** [comment]
@clarkjefcoat Can you verify? I know this doesn't fix the help modal issue but it should be merged in different PR's anyways.

**Comment by clarkjefcoat** [comment]
This does not appear to fix the menu issue.  I think the change is necessary, but it is evidently not enough.

**Comment by tonyalletag** [comment]
:+1:

**Comment by clarkjefcoat** [comment]
This coupled with #663 and #666 does fix the menu bar issue.

**Pull request merged**
